name 'jenkinsServer'
maintainer 'Keziah Zhou'
maintainer_email 'kezizhou@gmail.com'
license 'All Rights Reserved'
description 'Cookbook to install and start Jenkins server'
long_description 'Cookbook to install and start Jenkins server'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/kezizhou/jenkinsServer'
source_url 'https://github.com/kezizhou/jenkinsServer'
